---
# file: roles/common/tasks/main.yml

- name: unpack JDK manually as DEB shows error
  unarchive:
    src: "{{ java_package }}"
    dest: "{{ oracle_java_home }}"
    extra_opts: ['--strip-components=1']
  become: true


