---
# file: roles/common/tasks/main.yml

- name: Check archive file for message queue exists
#  become: true
#  become_user: "{{ app_user }}"
  stat:
    path: "/tmp/{{ java_package }}"
  register: java_package_exists

- block:
  - name: Get curl
    apt:
      name: curl
      update_cache: yes
      state: present
  
  - name: Download JDK as DEB installation shows error
    shell: "curl -L -o /tmp/{{ java_package }} {{ jave_package_url }}"

  when: not java_package_exists.stat.exists

- name: Create dir
  file:
    path: "{{ oracle_java_home }}"
    state: directory
  become: true

- name: Unpack JDK manually as DEB installation shows error
  unarchive:
    src: "/tmp/{{ java_package }}"
    dest: "{{ oracle_java_home }}"
    extra_opts: ['--strip-components=1']
  become: true

# - name: add PPA webupd8team repo
#   apt_repository:
#     repo: "ppa:webupd8team/java"
#     state: present
#   become: true
# 
# - name: accept Oracle license
#   shell: "echo oracle-java{{ oracle_java_version }}-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"
#   changed_when: no
#   become: true

# - name: ensure Java is installed
#   apt:
#     name="oracle-java{{ oracle_java_version }}-installer"
#     state={{ oracle_java_state }}
#     cache_valid_time={{ oracle_java_cache_valid_time }}
#     update_cache=yes
#   register: oracle_java_task_apt_install
#   become: true

# - name: set Java version as default
#   apt:
#     name="oracle-java{{ oracle_java_version }}-set-default"
#     state=latest
#   register: oracle_java_task_set_default
#   when: oracle_java_set_as_default
#   become: true
