apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatservice-deployment
  labels:
    app: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
      - name: chatservice
        image: 127.0.0.1:5001/chat_service:latest
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: chatservice-service
spec:
  selector:
    app: chatservice
  type: NodePort
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8080

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: chatservice-ingress
spec:
  backend:
    serviceName: chatservice-service
    servicePort: 80
