apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatservice-deployment
  labels:
    app: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
      - name: chatservice
        image: 127.0.0.1:5001/chat_service:latest
        env:
          - name: MQTTHOST
            value: '172.0.0.0:61613'
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          
---

kind: Service
apiVersion: v1
metadata:
  name: chatservice-service
spec:
  selector:
    app: chatservice
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
