dockerRepo = '127.0.0.1:5001'
imageName = 'chat_service'

node {
   def mvnHome
   stage('Preparation') { 
      git 'https://github.com/andjelx/chat_services.git'
      mvnHome = tool 'maven'
      env.JAVA_HOME="${tool 'jdk-8u101'}"
      env.PATH="${env.JAVA_HOME}/bin:${env.PATH}"
   }

   stage('Build') {
       dir('chat_service') {
         sh "'${mvnHome}/bin/mvn' clean package"
         sh "docker build . -t ${imageName} && docker tag ${imageName}:latest ${dockerRepo}/${imageName}:latest"
        }
      }

  stage('Docker Push') {
    sh "curl ${dockerRepo}; sleep 3" // Hack for repo initialisation
    sh "docker push ${dockerRepo}/${imageName}:latest"
  }
  
  stage('Results') {
      junit '**/target/surefire-reports/*.xml'
      archive 'target/*.jar'
  }
}